[2023-10-03T10:10:29.061+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: launches_getter.check_data_in_a_day scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T10:10:29.106+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: launches_getter.check_data_in_a_day scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T10:10:29.106+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:10:29.187+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): check_data_in_a_day> on 2023-09-30 00:00:00+00:00
[2023-10-03T10:10:29.194+0000] {standard_task_runner.py:57} INFO - Started process 3080 to run task
[2023-10-03T10:10:29.210+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'launches_getter', 'check_data_in_a_day', 'scheduled__2023-09-30T00:00:00+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/launches.py', '--cfg-path', '/tmp/tmphahh0ozb']
[2023-10-03T10:10:29.212+0000] {standard_task_runner.py:85} INFO - Job 184: Subtask check_data_in_a_day
[2023-10-03T10:10:29.519+0000] {task_command.py:410} INFO - Running <TaskInstance: launches_getter.check_data_in_a_day scheduled__2023-09-30T00:00:00+00:00 [running]> on host f21dc12153d8
[2023-10-03T10:10:30.138+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='launches_getter' AIRFLOW_CTX_TASK_ID='check_data_in_a_day' AIRFLOW_CTX_EXECUTION_DATE='2023-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-30T00:00:00+00:00'
[2023-10-03T10:10:30.177+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-10-03T10:10:30.212+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=launches_getter, task_id=check_data_in_a_day, execution_date=20230930T000000, start_date=20231003T101029, end_date=20231003T101030
[2023-10-03T10:10:30.304+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-10-03T10:10:30.545+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-10-03T12:31:49.659+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: launches_getter.check_data_in_a_day scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T12:31:49.800+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: launches_getter.check_data_in_a_day scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T12:31:49.808+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T12:31:49.933+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): check_data_in_a_day> on 2023-09-30 00:00:00+00:00
[2023-10-03T12:31:49.972+0000] {standard_task_runner.py:57} INFO - Started process 199 to run task
[2023-10-03T12:31:49.991+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'launches_getter', 'check_data_in_a_day', 'scheduled__2023-09-30T00:00:00+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/launches.py', '--cfg-path', '/tmp/tmpceyruljl']
[2023-10-03T12:31:50.012+0000] {standard_task_runner.py:85} INFO - Job 280: Subtask check_data_in_a_day
[2023-10-03T12:31:50.311+0000] {task_command.py:410} INFO - Running <TaskInstance: launches_getter.check_data_in_a_day scheduled__2023-09-30T00:00:00+00:00 [running]> on host f21dc12153d8
[2023-10-03T12:31:50.657+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='launches_getter' AIRFLOW_CTX_TASK_ID='check_data_in_a_day' AIRFLOW_CTX_EXECUTION_DATE='2023-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-30T00:00:00+00:00'
[2023-10-03T12:31:50.682+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-10-03T12:31:50.698+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=launches_getter, task_id=check_data_in_a_day, execution_date=20230930T000000, start_date=20231003T123149, end_date=20231003T123150
[2023-10-03T12:31:50.740+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-10-03T12:31:50.816+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
